
/* Generated by Interface Builder */

#import <Foundation/NSObject.h>
#import <Foundation/NSUserDefaults.h>
#import <AppKit/NSGraphics.h>
#import "EnvelopeView.h"

@interface EEController:NSObject
{
    id myListener;
    IBOutlet NSPanel *infoPanel;
    IBOutlet NSPanel *helpPanel;
	
    IBOutlet NSSplitView *theSplitView;
    IBOutlet NSWindow *theWindow;
	
    IBOutlet id theOutputTypes;
	
    IBOutlet id thePoint;
    IBOutlet id theXCoord;
    IBOutlet id theYCoord;
    IBOutlet id theYrCoord;
    IBOutlet id theXMinCoord;
    IBOutlet id theYMinCoord;
    IBOutlet id theXMaxCoord;
    IBOutlet id theYMaxCoord;
    IBOutlet id theXSnapCoord;
    IBOutlet id theYSnapCoord;
    IBOutlet id theStickyPoint;
    IBOutlet id theSmoothing;
    IBOutlet id theSmoothSlider;
    IBOutlet id theGraphType;
    IBOutlet id theLinkX;
	
    EnvelopeView *theEnvelope;
    EnvelopeView *lastDeleted;
}

- (void)applicationDidFinishLaunching:(NSNotification *)notification;
- (IBAction)infoPanel:sender;
- (IBAction)helpPanel:sender;

- (IBAction)addEnvelope:sender;
- (IBAction)removeEnvelope:sender;
- (IBAction)unRemoveEnvelope:sender;

- (IBAction)copy:(id)sender;
- (IBAction)paste:(id)sender;

// Received from current envelope view to update panel info if necessary

- (IBAction)update:sender;
- updateCoords: sender at: (int)point;

// Messages received from panel buttons and pop up lists

- (IBAction)nextPoint:sender;
- (IBAction)previousPoint:sender;

- (IBAction)setPoint:sender;
- (IBAction)setXValue:sender;
- (IBAction)setYValue:sender;
- (IBAction)setYrValue:sender;
- (IBAction)setSmoothValue:sender;
- (IBAction)setSmoothFromSlider:sender;
- (void)broadcastXLimitsOf:envelope;
- (IBAction)setXMinValue:sender;
- (IBAction)setXMaxValue:sender;
- (IBAction)setYMinValue:sender;
- (IBAction)setYMaxValue:sender;
- (IBAction)setXSnapValue:sender;
- (IBAction)setYSnapValue:sender;
- (IBAction)setStickyPoint:sender;
- (IBAction)setGraphType:sender;
- (IBAction)setDrawSegmentsState:sender;
- (IBAction)setLinkX:sender;

- (IBAction)reScaleLimits:sender;

- (NSString *) getStyle;

@end
