
/* Generated by Interface Builder */

#import <Cocoa/Cocoa.h>
#import "Document.h"

@interface Distributor:NSObject <NSApplicationDelegate>
{
    IBOutlet NSWindow * infoPanel;
    IBOutlet id helpPanel;
    id openPanel;
    id savePanel;
    id tadList;
    NSMutableArray *docList;	
    PlayScore *scorePlayer;
}

- init;
- setTadList:theList;
- (IBAction)closeDoc:sender;
- (IBAction)openDoc:sender;
- (IBAction)saveDocAs:sender;
- (IBAction)saveDoc:sender;
- (IBAction)showHelp:sender;
- (IBAction)showInfo:sender;
- (IBAction)newDoc:sender;
- (IBAction)play:sender;
- (IBAction)stopPlay:sender;
- (Document *) findCurrent;

@end
