
/* Generated by Interface Builder */

#import "ModView.h"

@implementation ModView

@synthesize FFTControler;

- afterUp:(float*)data length:(int)aLength
{
    [FFTControler setMod:FuncTable];
    return self;
}

- (void)drawRect:(NSRect)dirtyRect
{
    NSRect newVis = self.visibleRect;

	[super drawRect:dirtyRect];
    if(!block)[FFTControler passDraw:newVis.origin.x tag:1.];
    else block = 0;
}

- drawSelfAux:(float)origin
{
    static NSRect newVis;
    static int first=1;

    if(first) { newVis = self.visibleRect; first = 0 ;}
    newVis.origin.x = origin;
    block = 1; 
    [self scrollRectToVisible:newVis];
    block = 0;
    return self;
}

@end
