#ifndef __MK_Wave_H___
#define __MK_Wave_H___

/* Generated by Interface Builder */

#import "FuncView.h"
#import "FFTControl.h"
#import <appkit/appkit.h>	

@class MKOrchestra;

@interface Wave:FuncView
{
    IBOutlet id fftView;
	MKOrchestra *anOrch;
    id aSP;
    id tableLook;	        /* Lookup Table*/
    id aNote;
    int *DSPTable;
    float frq,amp,pvib,rvib,pvibFrq;
    BOOL vibOn;
}

- setFftView:anObject;
- (IBAction)sawTooth:sender;
- (IBAction)triangle:sender;
- (IBAction)sine:sender;
- (IBAction)square:sender;
- (IBAction)sendFreq:sender;
- (IBAction)sendAmp:sender;
- afterDrag:(float*) data length:(int)aLength offset:(int)anOffset;
- afterUp:(float*)data length:(int)aLength;
- (void)setSound:sender;
- startSound;
- stopSound;
- (IBAction)sendPVibFreq:sender;
- (IBAction)sendPVib:sender;
- (IBAction)sendRVib:sender;
- (IBAction)vibOnOff:sender;

@end
#endif
